name: ✅ Auto-Merge Valuable PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    # Check for mergeable PRs every 2 hours
    - cron: '0 */2 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  auto-merge-valuable:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔍 Find all open PRs (with mergeable & files)
        id: find-prs
        run: |
          # Fetch all open PRs, including the `mergeable` status and the list of changed files
          all_prs=$(gh pr list \
            --state open \
            --json number,title,author,mergeable,files \
            --limit 3000)

          # Store the entire JSON blob into an output variable
          echo "all_prs<<EOF" >> $GITHUB_OUTPUT
          echo "$all_prs"        >> $GITHUB_OUTPUT
          echo "EOF"             >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ✅ Auto-merge non-conflicting PRs
        run: |
          # ── STEP A: Dump the JSON into a local file so `jq` can parse it safely ──
          echo "${{ steps.find-prs.outputs.all_prs }}" > all_prs.json

          # ── STEP B: Loop over each PR record (base64-encoded) ──
          jq -r '.[] | @base64' all_prs.json | while IFS= read -r pr_data; do
            if [ -z "$pr_data" ]; then
              continue
            fi

            pr_json=$(echo "$pr_data" | base64 -d)
            pr_number=$(echo "$pr_json" | jq -r '.number')
            pr_title=$(echo "$pr_json" | jq -r '.title')
            pr_author=$(echo "$pr_json" | jq -r '.author.login')
            pr_mergeable=$(echo "$pr_json" | jq -r '.mergeable')

            # 1) Skip PRs that only modify contributors/contributorsList.js
            files_changed=$(echo "$pr_json" | jq -r '.files[].path // empty')
            if [ -z "$files_changed" ]; then
              # No files changed? Skip (edge case)
              continue
            fi

            contributors_only=true
            while IFS= read -r file; do
              if [ -n "$file" ] && [ "$file" != "contributors/contributorsList.js" ]; then
                contributors_only=false
                break
              fi
            done <<< "$files_changed"

            if [ "$contributors_only" = "true" ]; then
              # If the only changed file is contributorsList.js, skip this PR
              continue
            fi

            # 2) Only proceed if GitHub says "MERGEABLE"
            if [ "$pr_mergeable" != "MERGEABLE" ]; then
              echo "⚠️ Skipping PR #$pr_number (mergeable status: $pr_mergeable)"
              continue
            fi

            echo "🔄 Processing PR #$pr_number by @$pr_author — \"$pr_title\""
            echo "    • mergeable = $pr_mergeable"

            # 3) If the "valuable-contribution" label is not already present, add it
            has_label=$(gh pr view "$pr_number" --json labels \
              | jq -r '.labels[].name' \
              | grep -x "valuable-contribution" || echo "")

            if [ -z "$has_label" ]; then
              echo "    • Adding label “valuable-contribution”"
              gh pr edit "$pr_number" --add-label "valuable-contribution" || true
            fi

            # 4) Merge the PR and delete its branch
            echo "    • Attempting to merge PR #$pr_number"
            if gh pr merge "$pr_number" --merge --delete-branch; then
              echo "✅ Successfully merged PR #$pr_number"
              gh pr comment "$pr_number" \
                --body "🚀 **Automatically merged!** Thank you @$pr_author for your contribution. 🎉 #AutoMerge" \
                || true
            else
              echo "❌ Failed to merge PR #$pr_number"
            fi

            # Pause to avoid hitting GitHub’s rate limits
            sleep 2
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📊 Summary
        run: |
          echo "🤖 Auto-merge workflow completed!"
          contributor_count=$(grep -c "id:" contributors/contributorsList.js || echo 0)
          echo "📊 Total Contributors (lines in contributorsList.js): $contributor_count"
          echo "✅ Attempted to merge all non-conflicting PRs"
